apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ml-service.fullname" . }}
  labels: {{- include "ml-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{- include "ml-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "ml-service.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: ml
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
              name: http
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}


