apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-service.fullname" . }}
  labels: {{- include "app-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector: {{- include "app-service.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http


